services:
  app:
    build: .
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    # image: <mongodb-community-server>
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata: