services:
  app:
    build: .
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests 
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  test:
    build: .
    command: pytest tests/ --maxfail=1 --disable-warnings -v
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    # image: <mongodb-community-server>
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db