name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ktaba/Iris

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Set up docker-compose
      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # 4. Build docker-compose services
      - name: Build services
        run: docker-compose build

      # 5. Run tests
      - name: Run tests
        run: docker-compose run --rm test

      # 6. Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Build final production image (only app)
      - name: Build app image
        run: docker build -t $IMAGE_NAME .

      # 8. Push Docker image
      - name: Push app image to Docker Hub
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
